provider: pagerduty
major-version: 4
env:
  PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
makeTemplate: bridged
team: ecosystem
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: time
    version: "0.0.15"
pulumiConvert: 1
