provider: pagerduty
major-version: 4
esc:
    enabled: true
env:
    PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
