// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pagerduty.Outputs
{

    [OutputType]
    public sealed class RulesetRuleVariable
    {
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.RulesetRuleVariableParameter> Parameters;
        public readonly string? Type;

        [OutputConstructor]
        private RulesetRuleVariable(
            string? name,

            ImmutableArray<Outputs.RulesetRuleVariableParameter> parameters,

            string? type)
        {
            Name = name;
            Parameters = parameters;
            Type = type;
        }
    }
}
