// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pagerduty.Outputs
{

    [OutputType]
    public sealed class RulesetRuleTimeFrameActiveBetween
    {
        /// <summary>
        /// Ending of the scheduled time when the rule should execute.  Unix timestamp in milliseconds.
        /// </summary>
        public readonly int? EndTime;
        public readonly int? StartTime;

        [OutputConstructor]
        private RulesetRuleTimeFrameActiveBetween(
            int? endTime,

            int? startTime)
        {
            EndTime = endTime;
            StartTime = startTime;
        }
    }
}
