// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pagerduty.Outputs
{

    [OutputType]
    public sealed class SlackConnectionConfig
    {
        public readonly ImmutableArray<string> Events;
        public readonly ImmutableArray<string> Priorities;
        public readonly string? Urgency;

        [OutputConstructor]
        private SlackConnectionConfig(
            ImmutableArray<string> events,

            ImmutableArray<string> priorities,

            string? urgency)
        {
            Events = events;
            Priorities = priorities;
            Urgency = urgency;
        }
    }
}
