// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetIncidentTypePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetIncidentTypePlainArgs Empty = new GetIncidentTypePlainArgs();

    @Import(name="displayName", required=true)
    private String displayName;

    public String displayName() {
        return this.displayName;
    }

    private GetIncidentTypePlainArgs() {}

    private GetIncidentTypePlainArgs(GetIncidentTypePlainArgs $) {
        this.displayName = $.displayName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetIncidentTypePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetIncidentTypePlainArgs $;

        public Builder() {
            $ = new GetIncidentTypePlainArgs();
        }

        public Builder(GetIncidentTypePlainArgs defaults) {
            $ = new GetIncidentTypePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder displayName(String displayName) {
            $.displayName = displayName;
            return this;
        }

        public GetIncidentTypePlainArgs build() {
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("GetIncidentTypePlainArgs", "displayName");
            }
            return $;
        }
    }

}
