// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetJiraCloudAccountMappingArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetJiraCloudAccountMappingArgs Empty = new GetJiraCloudAccountMappingArgs();

    /**
     * The service name to use to find a service in the PagerDuty API.
     * 
     */
    @Import(name="subdomain", required=true)
    private Output<String> subdomain;

    /**
     * @return The service name to use to find a service in the PagerDuty API.
     * 
     */
    public Output<String> subdomain() {
        return this.subdomain;
    }

    private GetJiraCloudAccountMappingArgs() {}

    private GetJiraCloudAccountMappingArgs(GetJiraCloudAccountMappingArgs $) {
        this.subdomain = $.subdomain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetJiraCloudAccountMappingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetJiraCloudAccountMappingArgs $;

        public Builder() {
            $ = new GetJiraCloudAccountMappingArgs();
        }

        public Builder(GetJiraCloudAccountMappingArgs defaults) {
            $ = new GetJiraCloudAccountMappingArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param subdomain The service name to use to find a service in the PagerDuty API.
         * 
         * @return builder
         * 
         */
        public Builder subdomain(Output<String> subdomain) {
            $.subdomain = subdomain;
            return this;
        }

        /**
         * @param subdomain The service name to use to find a service in the PagerDuty API.
         * 
         * @return builder
         * 
         */
        public Builder subdomain(String subdomain) {
            return subdomain(Output.of(subdomain));
        }

        public GetJiraCloudAccountMappingArgs build() {
            if ($.subdomain == null) {
                throw new MissingRequiredPropertyException("GetJiraCloudAccountMappingArgs", "subdomain");
            }
            return $;
        }
    }

}
