// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.pagerduty.inputs.ServiceIntegrationEmailParserMatchPredicatePredicateArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceIntegrationEmailParserMatchPredicateArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceIntegrationEmailParserMatchPredicateArgs Empty = new ServiceIntegrationEmailParserMatchPredicateArgs();

    @Import(name="predicates")
    private @Nullable Output<List<ServiceIntegrationEmailParserMatchPredicatePredicateArgs>> predicates;

    public Optional<Output<List<ServiceIntegrationEmailParserMatchPredicatePredicateArgs>>> predicates() {
        return Optional.ofNullable(this.predicates);
    }

    /**
     * Can be `any` or `all`.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Can be `any` or `all`.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private ServiceIntegrationEmailParserMatchPredicateArgs() {}

    private ServiceIntegrationEmailParserMatchPredicateArgs(ServiceIntegrationEmailParserMatchPredicateArgs $) {
        this.predicates = $.predicates;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceIntegrationEmailParserMatchPredicateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceIntegrationEmailParserMatchPredicateArgs $;

        public Builder() {
            $ = new ServiceIntegrationEmailParserMatchPredicateArgs();
        }

        public Builder(ServiceIntegrationEmailParserMatchPredicateArgs defaults) {
            $ = new ServiceIntegrationEmailParserMatchPredicateArgs(Objects.requireNonNull(defaults));
        }

        public Builder predicates(@Nullable Output<List<ServiceIntegrationEmailParserMatchPredicatePredicateArgs>> predicates) {
            $.predicates = predicates;
            return this;
        }

        public Builder predicates(List<ServiceIntegrationEmailParserMatchPredicatePredicateArgs> predicates) {
            return predicates(Output.of(predicates));
        }

        public Builder predicates(ServiceIntegrationEmailParserMatchPredicatePredicateArgs... predicates) {
            return predicates(List.of(predicates));
        }

        /**
         * @param type Can be `any` or `all`.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Can be `any` or `all`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ServiceIntegrationEmailParserMatchPredicateArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ServiceIntegrationEmailParserMatchPredicateArgs", "type");
            }
            return $;
        }
    }

}
