// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceEventRuleActionsSuspendArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceEventRuleActionsSuspendArgs Empty = new ServiceEventRuleActionsSuspendArgs();

    /**
     * The value for the operation. For example, an RE2 regular expression for regex-type variables.
     * 
     */
    @Import(name="value")
    private @Nullable Output<Integer> value;

    /**
     * @return The value for the operation. For example, an RE2 regular expression for regex-type variables.
     * 
     */
    public Optional<Output<Integer>> value() {
        return Optional.ofNullable(this.value);
    }

    private ServiceEventRuleActionsSuspendArgs() {}

    private ServiceEventRuleActionsSuspendArgs(ServiceEventRuleActionsSuspendArgs $) {
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceEventRuleActionsSuspendArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceEventRuleActionsSuspendArgs $;

        public Builder() {
            $ = new ServiceEventRuleActionsSuspendArgs();
        }

        public Builder(ServiceEventRuleActionsSuspendArgs defaults) {
            $ = new ServiceEventRuleActionsSuspendArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param value The value for the operation. For example, an RE2 regular expression for regex-type variables.
         * 
         * @return builder
         * 
         */
        public Builder value(@Nullable Output<Integer> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value The value for the operation. For example, an RE2 regular expression for regex-type variables.
         * 
         * @return builder
         * 
         */
        public Builder value(Integer value) {
            return value(Output.of(value));
        }

        public ServiceEventRuleActionsSuspendArgs build() {
            return $;
        }
    }

}
