// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.pagerduty.inputs.ServiceIntegrationEmailParserMatchPredicateArgs;
import com.pulumi.pagerduty.inputs.ServiceIntegrationEmailParserValueExtractorArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceIntegrationEmailParserArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceIntegrationEmailParserArgs Empty = new ServiceIntegrationEmailParserArgs();

    /**
     * Can be `resolve` or `trigger`.
     * 
     */
    @Import(name="action", required=true)
    private Output<String> action;

    /**
     * @return Can be `resolve` or `trigger`.
     * 
     */
    public Output<String> action() {
        return this.action;
    }

    /**
     * The ID of the service integration.
     * 
     */
    @Import(name="id")
    private @Nullable Output<Integer> id;

    /**
     * @return The ID of the service integration.
     * 
     */
    public Optional<Output<Integer>> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="matchPredicate", required=true)
    private Output<ServiceIntegrationEmailParserMatchPredicateArgs> matchPredicate;

    public Output<ServiceIntegrationEmailParserMatchPredicateArgs> matchPredicate() {
        return this.matchPredicate;
    }

    @Import(name="valueExtractors")
    private @Nullable Output<List<ServiceIntegrationEmailParserValueExtractorArgs>> valueExtractors;

    public Optional<Output<List<ServiceIntegrationEmailParserValueExtractorArgs>>> valueExtractors() {
        return Optional.ofNullable(this.valueExtractors);
    }

    private ServiceIntegrationEmailParserArgs() {}

    private ServiceIntegrationEmailParserArgs(ServiceIntegrationEmailParserArgs $) {
        this.action = $.action;
        this.id = $.id;
        this.matchPredicate = $.matchPredicate;
        this.valueExtractors = $.valueExtractors;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceIntegrationEmailParserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceIntegrationEmailParserArgs $;

        public Builder() {
            $ = new ServiceIntegrationEmailParserArgs();
        }

        public Builder(ServiceIntegrationEmailParserArgs defaults) {
            $ = new ServiceIntegrationEmailParserArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param action Can be `resolve` or `trigger`.
         * 
         * @return builder
         * 
         */
        public Builder action(Output<String> action) {
            $.action = action;
            return this;
        }

        /**
         * @param action Can be `resolve` or `trigger`.
         * 
         * @return builder
         * 
         */
        public Builder action(String action) {
            return action(Output.of(action));
        }

        /**
         * @param id The ID of the service integration.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<Integer> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the service integration.
         * 
         * @return builder
         * 
         */
        public Builder id(Integer id) {
            return id(Output.of(id));
        }

        public Builder matchPredicate(Output<ServiceIntegrationEmailParserMatchPredicateArgs> matchPredicate) {
            $.matchPredicate = matchPredicate;
            return this;
        }

        public Builder matchPredicate(ServiceIntegrationEmailParserMatchPredicateArgs matchPredicate) {
            return matchPredicate(Output.of(matchPredicate));
        }

        public Builder valueExtractors(@Nullable Output<List<ServiceIntegrationEmailParserValueExtractorArgs>> valueExtractors) {
            $.valueExtractors = valueExtractors;
            return this;
        }

        public Builder valueExtractors(List<ServiceIntegrationEmailParserValueExtractorArgs> valueExtractors) {
            return valueExtractors(Output.of(valueExtractors));
        }

        public Builder valueExtractors(ServiceIntegrationEmailParserValueExtractorArgs... valueExtractors) {
            return valueExtractors(List.of(valueExtractors));
        }

        public ServiceIntegrationEmailParserArgs build() {
            $.action = Objects.requireNonNull($.action, "expected parameter 'action' to be non-null");
            $.matchPredicate = Objects.requireNonNull($.matchPredicate, "expected parameter 'matchPredicate' to be non-null");
            return $;
        }
    }

}
