// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class EventOrchestrationServiceSetRuleActionsPagerdutyAutomationAction {
    /**
     * @return Id of the Process Automation action to be triggered.
     * 
     */
    private String actionId;

    private EventOrchestrationServiceSetRuleActionsPagerdutyAutomationAction() {}
    /**
     * @return Id of the Process Automation action to be triggered.
     * 
     */
    public String actionId() {
        return this.actionId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EventOrchestrationServiceSetRuleActionsPagerdutyAutomationAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String actionId;
        public Builder() {}
        public Builder(EventOrchestrationServiceSetRuleActionsPagerdutyAutomationAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.actionId = defaults.actionId;
        }

        @CustomType.Setter
        public Builder actionId(String actionId) {
            this.actionId = Objects.requireNonNull(actionId);
            return this;
        }
        public EventOrchestrationServiceSetRuleActionsPagerdutyAutomationAction build() {
            final var _resultValue = new EventOrchestrationServiceSetRuleActionsPagerdutyAutomationAction();
            _resultValue.actionId = actionId;
            return _resultValue;
        }
    }
}
