// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetBusinessServiceResult {
    /**
     * @return The ID of the found business service.
     * 
     */
    private String id;
    /**
     * @return The short name of the found business service.
     * 
     */
    private String name;
    /**
     * @return The type of object. The value returned will be `businessService`. Can be used for passing to a service dependency.
     * 
     */
    private String type;

    private GetBusinessServiceResult() {}
    /**
     * @return The ID of the found business service.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The short name of the found business service.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The type of object. The value returned will be `businessService`. Can be used for passing to a service dependency.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetBusinessServiceResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String name;
        private String type;
        public Builder() {}
        public Builder(GetBusinessServiceResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetBusinessServiceResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetBusinessServiceResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetBusinessServiceResult", "type");
            }
            this.type = type;
            return this;
        }
        public GetBusinessServiceResult build() {
            final var _resultValue = new GetBusinessServiceResult();
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
