// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetEventOrchestrationsEventOrchestrationIntegrationParameter {
    /**
     * @return Routing key that routes to this Orchestration.
     * 
     */
    private String routingKey;
    /**
     * @return Type of the routing key. `global` is the default type.
     * 
     */
    private String type;

    private GetEventOrchestrationsEventOrchestrationIntegrationParameter() {}
    /**
     * @return Routing key that routes to this Orchestration.
     * 
     */
    public String routingKey() {
        return this.routingKey;
    }
    /**
     * @return Type of the routing key. `global` is the default type.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEventOrchestrationsEventOrchestrationIntegrationParameter defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String routingKey;
        private String type;
        public Builder() {}
        public Builder(GetEventOrchestrationsEventOrchestrationIntegrationParameter defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.routingKey = defaults.routingKey;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder routingKey(String routingKey) {
            this.routingKey = Objects.requireNonNull(routingKey);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public GetEventOrchestrationsEventOrchestrationIntegrationParameter build() {
            final var o = new GetEventOrchestrationsEventOrchestrationIntegrationParameter();
            o.routingKey = routingKey;
            o.type = type;
            return o;
        }
    }
}
