// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetIncidentCustomFieldResult {
    private String dataType;
    private String description;
    private String displayName;
    private String fieldType;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String name;

    private GetIncidentCustomFieldResult() {}
    public String dataType() {
        return this.dataType;
    }
    public String description() {
        return this.description;
    }
    public String displayName() {
        return this.displayName;
    }
    public String fieldType() {
        return this.fieldType;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetIncidentCustomFieldResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String dataType;
        private String description;
        private String displayName;
        private String fieldType;
        private String id;
        private String name;
        public Builder() {}
        public Builder(GetIncidentCustomFieldResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataType = defaults.dataType;
    	      this.description = defaults.description;
    	      this.displayName = defaults.displayName;
    	      this.fieldType = defaults.fieldType;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder dataType(String dataType) {
            this.dataType = Objects.requireNonNull(dataType);
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder displayName(String displayName) {
            this.displayName = Objects.requireNonNull(displayName);
            return this;
        }
        @CustomType.Setter
        public Builder fieldType(String fieldType) {
            this.fieldType = Objects.requireNonNull(fieldType);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public GetIncidentCustomFieldResult build() {
            final var _resultValue = new GetIncidentCustomFieldResult();
            _resultValue.dataType = dataType;
            _resultValue.description = description;
            _resultValue.displayName = displayName;
            _resultValue.fieldType = fieldType;
            _resultValue.id = id;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
