// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pagerduty.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RulesetRuleActionsSuspend {
    /**
     * @return Boolean value that indicates if the alert should be suppressed before the indicated threshold values are met.
     * 
     */
    private final @Nullable Integer value;

    @CustomType.Constructor
    private RulesetRuleActionsSuspend(@CustomType.Parameter("value") @Nullable Integer value) {
        this.value = value;
    }

    /**
     * @return Boolean value that indicates if the alert should be suppressed before the indicated threshold values are met.
     * 
     */
    public Optional<Integer> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RulesetRuleActionsSuspend defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Integer value;

        public Builder() {
    	      // Empty
        }

        public Builder(RulesetRuleActionsSuspend defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.value = defaults.value;
        }

        public Builder value(@Nullable Integer value) {
            this.value = value;
            return this;
        }        public RulesetRuleActionsSuspend build() {
            return new RulesetRuleActionsSuspend(value);
        }
    }
}
