// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Import
 *
 * Global Orchestration can be imported using the `id` of the Event Orchestration, e.g.
 *
 * ```sh
 *  $ pulumi import pagerduty:index/eventOrchestrationGlobal:EventOrchestrationGlobal global 1b49abe7-26db-4439-a715-c6d883acfb3e
 * ```
 */
export class EventOrchestrationGlobal extends pulumi.CustomResource {
    /**
     * Get an existing EventOrchestrationGlobal resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EventOrchestrationGlobalState, opts?: pulumi.CustomResourceOptions): EventOrchestrationGlobal {
        return new EventOrchestrationGlobal(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pagerduty:index/eventOrchestrationGlobal:EventOrchestrationGlobal';

    /**
     * Returns true if the given object is an instance of EventOrchestrationGlobal.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventOrchestrationGlobal {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventOrchestrationGlobal.__pulumiType;
    }

    /**
     * the `catchAll` actions will be applied if an Event reaches the end of any set without matching any rules in that set.
     */
    public readonly catchAll!: pulumi.Output<outputs.EventOrchestrationGlobalCatchAll>;
    /**
     * ID of the Event Orchestration to which this Global Orchestration belongs to.
     */
    public readonly eventOrchestration!: pulumi.Output<string>;
    /**
     * A Global Orchestration must contain at least a "start" set, but can contain any number of additional sets that are routed to by other rules to form a directional graph.
     */
    public readonly sets!: pulumi.Output<outputs.EventOrchestrationGlobalSet[]>;

    /**
     * Create a EventOrchestrationGlobal resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventOrchestrationGlobalArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EventOrchestrationGlobalArgs | EventOrchestrationGlobalState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EventOrchestrationGlobalState | undefined;
            resourceInputs["catchAll"] = state ? state.catchAll : undefined;
            resourceInputs["eventOrchestration"] = state ? state.eventOrchestration : undefined;
            resourceInputs["sets"] = state ? state.sets : undefined;
        } else {
            const args = argsOrState as EventOrchestrationGlobalArgs | undefined;
            if ((!args || args.catchAll === undefined) && !opts.urn) {
                throw new Error("Missing required property 'catchAll'");
            }
            if ((!args || args.eventOrchestration === undefined) && !opts.urn) {
                throw new Error("Missing required property 'eventOrchestration'");
            }
            if ((!args || args.sets === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sets'");
            }
            resourceInputs["catchAll"] = args ? args.catchAll : undefined;
            resourceInputs["eventOrchestration"] = args ? args.eventOrchestration : undefined;
            resourceInputs["sets"] = args ? args.sets : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EventOrchestrationGlobal.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EventOrchestrationGlobal resources.
 */
export interface EventOrchestrationGlobalState {
    /**
     * the `catchAll` actions will be applied if an Event reaches the end of any set without matching any rules in that set.
     */
    catchAll?: pulumi.Input<inputs.EventOrchestrationGlobalCatchAll>;
    /**
     * ID of the Event Orchestration to which this Global Orchestration belongs to.
     */
    eventOrchestration?: pulumi.Input<string>;
    /**
     * A Global Orchestration must contain at least a "start" set, but can contain any number of additional sets that are routed to by other rules to form a directional graph.
     */
    sets?: pulumi.Input<pulumi.Input<inputs.EventOrchestrationGlobalSet>[]>;
}

/**
 * The set of arguments for constructing a EventOrchestrationGlobal resource.
 */
export interface EventOrchestrationGlobalArgs {
    /**
     * the `catchAll` actions will be applied if an Event reaches the end of any set without matching any rules in that set.
     */
    catchAll: pulumi.Input<inputs.EventOrchestrationGlobalCatchAll>;
    /**
     * ID of the Event Orchestration to which this Global Orchestration belongs to.
     */
    eventOrchestration: pulumi.Input<string>;
    /**
     * A Global Orchestration must contain at least a "start" set, but can contain any number of additional sets that are routed to by other rules to form a directional graph.
     */
    sets: pulumi.Input<pulumi.Input<inputs.EventOrchestrationGlobalSet>[]>;
}
