// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A special case for [extension](https://developer.pagerduty.com/api-reference/b3A6Mjc0ODEzMw-create-an-extension) for ServiceNow.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pagerduty from "@pulumi/pagerduty";
 *
 * const servicenow = pagerduty.getExtensionSchema({
 *     name: "ServiceNow (v7)",
 * });
 * const example = new pagerduty.User("example", {
 *     name: "Howard James",
 *     email: "howard.james@example.domain",
 * });
 * const exampleEscalationPolicy = new pagerduty.EscalationPolicy("example", {
 *     name: "Engineering Escalation Policy",
 *     numLoops: 2,
 *     rules: [{
 *         escalationDelayInMinutes: 10,
 *         targets: [{
 *             type: "user",
 *             id: example.id,
 *         }],
 *     }],
 * });
 * const exampleService = new pagerduty.Service("example", {
 *     name: "My Web App",
 *     autoResolveTimeout: "14400",
 *     acknowledgementTimeout: "600",
 *     escalationPolicy: exampleEscalationPolicy.id,
 * });
 * const snow = new pagerduty.ExtensionServiceNow("snow", {
 *     name: "My Web App Extension",
 *     extensionSchema: servicenow.then(servicenow => servicenow.id),
 *     extensionObjects: [exampleService.id],
 *     snowUser: "meeps",
 *     snowPassword: "zorz",
 *     syncOptions: "manual_sync",
 *     target: "https://foo.servicenow.com/webhook_foo",
 *     taskType: "incident",
 *     referer: "None",
 * });
 * ```
 *
 * ## Import
 *
 * Extensions can be imported using the id.e.g.
 *
 * ```sh
 * $ pulumi import pagerduty:index/extensionServiceNow:ExtensionServiceNow main PLBP09X
 * ```
 */
export class ExtensionServiceNow extends pulumi.CustomResource {
    /**
     * Get an existing ExtensionServiceNow resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ExtensionServiceNowState, opts?: pulumi.CustomResourceOptions): ExtensionServiceNow {
        return new ExtensionServiceNow(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pagerduty:index/extensionServiceNow:ExtensionServiceNow';

    /**
     * Returns true if the given object is an instance of ExtensionServiceNow.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ExtensionServiceNow {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ExtensionServiceNow.__pulumiType;
    }

    declare public readonly endpointUrl: pulumi.Output<string | undefined>;
    /**
     * This is the objects for which the extension applies (An array of service ids).
     */
    declare public readonly extensionObjects: pulumi.Output<string[]>;
    /**
     * This is the schema for this extension.
     */
    declare public readonly extensionSchema: pulumi.Output<string>;
    /**
     * URL at which the entity is uniquely displayed in the Web app.
     */
    declare public /*out*/ readonly htmlUrl: pulumi.Output<string>;
    /**
     * The name of the service extension.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ServiceNow referer.
     */
    declare public readonly referer: pulumi.Output<string>;
    /**
     * The ServiceNow password.
     */
    declare public readonly snowPassword: pulumi.Output<string>;
    /**
     * The ServiceNow username.
     */
    declare public readonly snowUser: pulumi.Output<string>;
    /**
     * A short-form, server-generated string that provides succinct, important information about an object suitable for primary labeling of an entity in a client. In many cases, this will be identical to `name`, though it is not intended to be an identifier.
     */
    declare public readonly summary: pulumi.Output<string>;
    /**
     * The ServiceNow sync option.
     */
    declare public readonly syncOptions: pulumi.Output<string>;
    /**
     * Target Webhook URL.
     */
    declare public readonly target: pulumi.Output<string>;
    /**
     * The ServiceNow task type, typically `incident`.
     */
    declare public readonly taskType: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a ExtensionServiceNow resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ExtensionServiceNowArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ExtensionServiceNowArgs | ExtensionServiceNowState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ExtensionServiceNowState | undefined;
            resourceInputs["endpointUrl"] = state?.endpointUrl;
            resourceInputs["extensionObjects"] = state?.extensionObjects;
            resourceInputs["extensionSchema"] = state?.extensionSchema;
            resourceInputs["htmlUrl"] = state?.htmlUrl;
            resourceInputs["name"] = state?.name;
            resourceInputs["referer"] = state?.referer;
            resourceInputs["snowPassword"] = state?.snowPassword;
            resourceInputs["snowUser"] = state?.snowUser;
            resourceInputs["summary"] = state?.summary;
            resourceInputs["syncOptions"] = state?.syncOptions;
            resourceInputs["target"] = state?.target;
            resourceInputs["taskType"] = state?.taskType;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as ExtensionServiceNowArgs | undefined;
            if (args?.extensionObjects === undefined && !opts.urn) {
                throw new Error("Missing required property 'extensionObjects'");
            }
            if (args?.extensionSchema === undefined && !opts.urn) {
                throw new Error("Missing required property 'extensionSchema'");
            }
            if (args?.referer === undefined && !opts.urn) {
                throw new Error("Missing required property 'referer'");
            }
            if (args?.snowPassword === undefined && !opts.urn) {
                throw new Error("Missing required property 'snowPassword'");
            }
            if (args?.snowUser === undefined && !opts.urn) {
                throw new Error("Missing required property 'snowUser'");
            }
            if (args?.syncOptions === undefined && !opts.urn) {
                throw new Error("Missing required property 'syncOptions'");
            }
            if (args?.target === undefined && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            if (args?.taskType === undefined && !opts.urn) {
                throw new Error("Missing required property 'taskType'");
            }
            resourceInputs["endpointUrl"] = args?.endpointUrl ? pulumi.secret(args.endpointUrl) : undefined;
            resourceInputs["extensionObjects"] = args?.extensionObjects;
            resourceInputs["extensionSchema"] = args?.extensionSchema;
            resourceInputs["name"] = args?.name;
            resourceInputs["referer"] = args?.referer;
            resourceInputs["snowPassword"] = args?.snowPassword ? pulumi.secret(args.snowPassword) : undefined;
            resourceInputs["snowUser"] = args?.snowUser;
            resourceInputs["summary"] = args?.summary;
            resourceInputs["syncOptions"] = args?.syncOptions;
            resourceInputs["target"] = args?.target;
            resourceInputs["taskType"] = args?.taskType;
            resourceInputs["type"] = args?.type;
            resourceInputs["htmlUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["endpointUrl", "snowPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ExtensionServiceNow.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ExtensionServiceNow resources.
 */
export interface ExtensionServiceNowState {
    endpointUrl?: pulumi.Input<string>;
    /**
     * This is the objects for which the extension applies (An array of service ids).
     */
    extensionObjects?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * This is the schema for this extension.
     */
    extensionSchema?: pulumi.Input<string>;
    /**
     * URL at which the entity is uniquely displayed in the Web app.
     */
    htmlUrl?: pulumi.Input<string>;
    /**
     * The name of the service extension.
     */
    name?: pulumi.Input<string>;
    /**
     * The ServiceNow referer.
     */
    referer?: pulumi.Input<string>;
    /**
     * The ServiceNow password.
     */
    snowPassword?: pulumi.Input<string>;
    /**
     * The ServiceNow username.
     */
    snowUser?: pulumi.Input<string>;
    /**
     * A short-form, server-generated string that provides succinct, important information about an object suitable for primary labeling of an entity in a client. In many cases, this will be identical to `name`, though it is not intended to be an identifier.
     */
    summary?: pulumi.Input<string>;
    /**
     * The ServiceNow sync option.
     */
    syncOptions?: pulumi.Input<string>;
    /**
     * Target Webhook URL.
     */
    target?: pulumi.Input<string>;
    /**
     * The ServiceNow task type, typically `incident`.
     */
    taskType?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ExtensionServiceNow resource.
 */
export interface ExtensionServiceNowArgs {
    endpointUrl?: pulumi.Input<string>;
    /**
     * This is the objects for which the extension applies (An array of service ids).
     */
    extensionObjects: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * This is the schema for this extension.
     */
    extensionSchema: pulumi.Input<string>;
    /**
     * The name of the service extension.
     */
    name?: pulumi.Input<string>;
    /**
     * The ServiceNow referer.
     */
    referer: pulumi.Input<string>;
    /**
     * The ServiceNow password.
     */
    snowPassword: pulumi.Input<string>;
    /**
     * The ServiceNow username.
     */
    snowUser: pulumi.Input<string>;
    /**
     * A short-form, server-generated string that provides succinct, important information about an object suitable for primary labeling of an entity in a client. In many cases, this will be identical to `name`, though it is not intended to be an identifier.
     */
    summary?: pulumi.Input<string>;
    /**
     * The ServiceNow sync option.
     */
    syncOptions: pulumi.Input<string>;
    /**
     * Target Webhook URL.
     */
    target: pulumi.Input<string>;
    /**
     * The ServiceNow task type, typically `incident`.
     */
    taskType: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}
