// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pagerduty from "@pulumi/pagerduty";
 *
 * const example = pagerduty.getRuleset({
 *     name: "My Ruleset",
 * });
 * const foo = new pagerduty.RulesetRule("foo", {
 *     ruleset: example.then(example => example.id),
 *     position: 0,
 *     disabled: false,
 *     conditions: {
 *         operator: "and",
 *         subconditions: [
 *             {
 *                 operator: "contains",
 *                 parameters: [{
 *                     value: "disk space",
 *                     path: "payload.summary",
 *                 }],
 *             },
 *             {
 *                 operator: "contains",
 *                 parameters: [{
 *                     value: "db",
 *                     path: "payload.source",
 *                 }],
 *             },
 *         ],
 *     },
 *     actions: {
 *         routes: [{
 *             value: "P5DTL0K",
 *         }],
 *     },
 * });
 * ```
 *
 * ### Default Global Ruleset
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pagerduty from "@pulumi/pagerduty";
 *
 * const defaultGlobal = pagerduty.getRuleset({
 *     name: "Default Global",
 * });
 * ```
 */
export function getRuleset(args: GetRulesetArgs, opts?: pulumi.InvokeOptions): Promise<GetRulesetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pagerduty:index/getRuleset:getRuleset", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getRuleset.
 */
export interface GetRulesetArgs {
    /**
     * The name of the ruleset to find in the PagerDuty API.
     */
    name: string;
}

/**
 * A collection of values returned by getRuleset.
 */
export interface GetRulesetResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the found ruleset.
     */
    readonly name: string;
    /**
     * Routing keys routed to this ruleset.
     */
    readonly routingKeys: string[];
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pagerduty from "@pulumi/pagerduty";
 *
 * const example = pagerduty.getRuleset({
 *     name: "My Ruleset",
 * });
 * const foo = new pagerduty.RulesetRule("foo", {
 *     ruleset: example.then(example => example.id),
 *     position: 0,
 *     disabled: false,
 *     conditions: {
 *         operator: "and",
 *         subconditions: [
 *             {
 *                 operator: "contains",
 *                 parameters: [{
 *                     value: "disk space",
 *                     path: "payload.summary",
 *                 }],
 *             },
 *             {
 *                 operator: "contains",
 *                 parameters: [{
 *                     value: "db",
 *                     path: "payload.source",
 *                 }],
 *             },
 *         ],
 *     },
 *     actions: {
 *         routes: [{
 *             value: "P5DTL0K",
 *         }],
 *     },
 * });
 * ```
 *
 * ### Default Global Ruleset
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pagerduty from "@pulumi/pagerduty";
 *
 * const defaultGlobal = pagerduty.getRuleset({
 *     name: "Default Global",
 * });
 * ```
 */
export function getRulesetOutput(args: GetRulesetOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRulesetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pagerduty:index/getRuleset:getRuleset", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getRuleset.
 */
export interface GetRulesetOutputArgs {
    /**
     * The name of the ruleset to find in the PagerDuty API.
     */
    name: pulumi.Input<string>;
}
